### ISSUE TITLE
Please remove the google analytics "feature"

### ISSUE THREAD

**Issue by markiewb** [ben-gibson/jetbrains-open-in-git-host#34]
Why has this "feature" been included? 

I do not want that a simple external plugin tracks all calls to the GitBlit-Server of my company. It gathers all the fully qualified path names of the files I opened using this plugin.

So your plugin got worthless for me. In the worst case I have to fork your plugin and remove the relevant code. Can you please remove the analytics!

**Comment by ben-gibson** [comment]
> Why has this "feature" been included?

Because I wanted it?

> I do not want that a simple external plugin tracks all calls to the GitBlit-Server of my company. It gathers all the fully qualified path names of the files I opened using this plugin.

The current version, `1.6.4`, only passes the version number, the host e.g. `GitHub`, `GitLab`, `BitBucket` selected from the settings, and the action e.g. `Open` or `Open and Copy`. Collecting usage statistics using Google Analytics has been suggested by JetBrains, see [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206753105-Detailed-Plugin-Usage-Statistics?page=1#community_comment_206657839).

> So your plugin got worthless for me. In the worst case I have to fork your plugin and remove the relevant code.

Feel free to use a different plugin or make the fork.

> Can you please remove the analytics!

No

Thanks

**Comment by markiewb** [comment]
@ben-gibson: Let's be constructive. How about checkbox in the options panel? It would be checked by default (= tracking enabled). Would you accept such a pull-request?

**Comment by markiewb** [comment]
For the record. It has been removed by https://github.com/ben-gibson/jetbrains-open-in-git-host/pull/36
